"""Application-owned consolidated knowledge catalog boundary."""

from .api import CatalogReader, get_catalog_reader
from .importer import KnowledgeCatalogImportResult, import_consolidated_release
from .persistence import (
    CatalogBondEnthalpyRow,
    CatalogKnowledgeLinkRow,
    CatalogKnowledgeRecordRow,
    CatalogPhaseTransitionRow,
    CatalogReactionParticipantRow,
    CatalogReactionRow,
    CatalogReleaseArtifactRow,
    CatalogReleaseRow,
    CatalogSourceAttributionRow,
    CatalogSourceCrosswalkRow,
    CatalogSpeciesPhaseFactRow,
    CatalogSpeciesRow,
    CatalogSpeciesThermochemistryRow,
    CatalogStructureLinkRow,
    CatalogStructureRecordRow,
    CatalogTeachingProjectionRow,
    KnowledgeCatalogBase,
)
from .postgres import PostgresCatalogReader
from .read_model import (
    CatalogBondEnthalpyResult,
    CatalogKnowledgeLinkResult,
    CatalogKnowledgeResult,
    CatalogReactionDetail,
    CatalogReactionParticipantResult,
    CatalogReactionResult,
    CatalogRelatedSpeciesResult,
    CatalogSourceAttributionResult,
    CatalogSpeciesPhaseFact,
    CatalogSpeciesResult,
    CatalogSpeciesThermochemistry,
    CatalogSpeciesThermochemistryContext,
    CatalogStructureEntry,
    CatalogStructureExploration,
)
from .release import (
    PINNED_RELEASE,
    PinnedRelease,
    ReleaseSourceIdentity,
    ReleaseValidationError,
    VerifiedArtifact,
    VerifiedRelease,
    read_git_source_identity,
    verify_release,
)

__all__ = [
    "PINNED_RELEASE",
    "CatalogBondEnthalpyResult",
    "CatalogBondEnthalpyRow",
    "CatalogKnowledgeLinkResult",
    "CatalogKnowledgeLinkRow",
    "CatalogKnowledgeRecordRow",
    "CatalogKnowledgeResult",
    "CatalogPhaseTransitionRow",
    "CatalogReactionDetail",
    "CatalogReactionParticipantResult",
    "CatalogReactionParticipantRow",
    "CatalogReactionResult",
    "CatalogReactionRow",
    "CatalogReader",
    "CatalogRelatedSpeciesResult",
    "CatalogReleaseArtifactRow",
    "CatalogReleaseRow",
    "CatalogSourceAttributionResult",
    "CatalogSourceAttributionRow",
    "CatalogSourceCrosswalkRow",
    "CatalogSpeciesPhaseFact",
    "CatalogSpeciesPhaseFactRow",
    "CatalogSpeciesResult",
    "CatalogSpeciesRow",
    "CatalogSpeciesThermochemistry",
    "CatalogSpeciesThermochemistryContext",
    "CatalogSpeciesThermochemistryRow",
    "CatalogStructureEntry",
    "CatalogStructureExploration",
    "CatalogStructureLinkRow",
    "CatalogStructureRecordRow",
    "CatalogTeachingProjectionRow",
    "KnowledgeCatalogBase",
    "KnowledgeCatalogImportResult",
    "PinnedRelease",
    "PostgresCatalogReader",
    "ReleaseSourceIdentity",
    "ReleaseValidationError",
    "VerifiedArtifact",
    "VerifiedRelease",
    "get_catalog_reader",
    "import_consolidated_release",
    "read_git_source_identity",
    "verify_release",
]
